Update for Chromium 117.0.5863.0
open-quantum-safe/boringssl pull request #103
Opened 2023-07-01 04:23 UTC by Raytonne

Please check [oqs-demos PR #210](https://github.com/open-quantum-safe/oqs-demos/pull/210)

2023-07-02 16:34 UTC, baentsch commented on include/openssl/evp.h
> +OPENSSL_EXPORT int oqs_verify_sig(EVP_PKEY *bssl_oqs_pkey, const uint8_t *sig,
This is not a good place for the function prototype: The next time `generate.py` is run, this code is deleted (everything between "OQS_TEMPLATE..._START" and "...END" -> Please move this code right before the "// EVP_PKEY_set_type sets..." comment.

2023-07-02 16:36 UTC, baentsch requested changes
Thanks for adding the verify function. Please change the place of the function prototype to avoid problems with the OQS integration code generator. Out of curiosity: How/why does this work with hybrid algorithms? The code seems to only cater for pure OQS algorithms...

2023-07-02 16:37 UTC, baentsch commented
> All _applicable_ interop tests (with the interop server at test.openquantumsafe.org) have passed.

Can you be specific in which those are? Surely not the x... hybrid KEMs, but what else doesn't work?

2023-07-04 18:23 UTC, baentsch approved these changes

2023-07-04 18:23 UTC, merged

2023-09-25 23:45 UTC, dstebila commented
@Raytonne Are you interested in doing another update of this boringssl fork to match the recent algorithm updates in liboqs?

2023-10-22 03:38 UTC, pi-314159 commented
@dstebila @baentsch  Just tested: current boringssl works with liboqs 0.9.0. Of course, there is no support for McEliece.
Since the interop server at test.openquantumsafe.org doesn't support McEliece, I guess there is no need to add McEliece to boringssl now?

2023-10-22 05:44 UTC, baentsch commented
> Just tested: current boringssl works with liboqs 0.9.0. 

Thanks for this check! 

>  there is no need to add McEliece to boringssl now?

Correct. Rationale: https://github.com/open-quantum-safe/oqs-provider/issues/191