Trust Token and time.h Update
open-quantum-safe/boringssl pull request #97
Opened 2023-03-14 06:19 UTC by Raytonne

These updates are required to build the latest Chromium.

+ [commit: 6cda656e4a2e1545e23b30dfb7dc05fe423e3f6c](https://boringssl.googlesource.com/boringssl/+/6cda656e4a2e1545e23b30dfb7dc05fe423e3f6c)
+ [commit: fa4555a8b665b222e5d73d4cda3d4bbfa8518457](https://boringssl.googlesource.com/boringssl/+/fa4555a8b665b222e5d73d4cda3d4bbfa8518457)
+ [commit: 80a243e07ef77156af66efa7d22ac35aba44c1b3](https://boringssl.googlesource.com/boringssl/+/80a243e07ef77156af66efa7d22ac35aba44c1b3)

2023-03-14 06:33 UTC, baentsch requested changes
Thanks for your contribution to update the code! Please be sure to also update the README as this statement probably is now incorrect:

> The fork is currently based on commit hash 387f82054c8ffa7d2b9e31d908586fbd47f34039 which has been verified to work with Chromium tag 100.0.4856.2.

This will probably mean that more files (from the more current boringssl commit) would need to be brought in with this PR, right? 

Please also ensure the CI passes. To facilitate this, you can fyi run the tests locally, e.g., by running `circleci local execute --job  static_oqs-static_bssl`

2023-03-23 09:21 UTC, baentsch approved these changes

2023-03-23 09:21 UTC, baentsch commented
@xvzcf I'll defer to your opinion on this: Please review and merge as you see fit.

2023-04-25 14:37 UTC, xvzcf commented
> Would it be possible to do a full update to [80a243e07ef77156af66efa7d22ac35aba44c1b3](https://boringssl.googlesource.com/boringssl/+/80a243e07ef77156af66efa7d22ac35aba44c1b3)? That might be the cleaner option.

Would you happen to have any updates on this by any chance?

2023-06-12 10:37 UTC, closed without merging